### ISSUE TITLE
Interface KVH Driver with Device

### ISSUE THREAD

**Issue by aruisdante** [RIVeR-Lab/kvh#12]
This is a catch-all issue for work related to getting the KVH driver interfacing with KVH devices over serial communications

**Comment by aruisdante** [comment]
@mitchellweb1 I'm passing this one off to you for now since I need to focus on working on the global planner. When you have time, please try and get the IMU communicating with the node and extracting the correct data from it.

**Comment by mitchellwills** [comment]
Ok I'm not feeling well today but I was planning on coming in tomorrow. Do you know if @velinddimitrov has finished the wiring harness yet?

**Comment by velinddimitrov** [comment]
Working on it today in lab.

**Comment by velinddimitrov** [comment]
Harness is done. I can show you on Monday how to plug it in. Should be in
the lab most of the day.

**Comment by mitchellwills** [comment]
fixed in  76d5b9e
