### ISSUE TITLE
dynamic_reconfigure prevents package compilation

### ISSUE THREAD

**Issue by aruisdante** [RIVeR-Lab/kvh#4]
Currently there is some kind of strange bug where if you add dynamic_reconfigure to CMakelist.txt, it prevents the actual executables from being built, even if there are no compile errors. Perhaps the package needs to be catkinized for DR to work in groovy?

**Comment by mitchellwills** [comment]
It would appear that bfl has not yet been catkinized. So it will have to wait to be catkinized

**Comment by aruisdante** [comment]
ahhhhh, so the problem was their tutorial. In it it says to use the catkin calls if you're using Groovy or later, not 'if you're using Groovy or later AND building with Catkin'. Did you check to make sure your compiles were actually updating the exe? Before the build would pass, but the exe wouldn't actually change.

**Comment by mitchellwills** [comment]
Yah I did a clean build and it built and ran up until the seg fault that you got. Besides that it seems to happen like 20 calls into the update call I didn't find out anything useful
