### ISSUE TITLE
Build a system to load sensor parameters from a config file

### ISSUE THREAD

**Issue by aruisdante** [RIVeR-Lab/kvh#8]
We need to build some type of system to load sensor parameters from a config file. Good candidate would be boost's PropertyTree I think. Parameters would include anything needed for serial communications with the device, as well as things like sensor noise/covar etc. We'll use this to load the correct parameters based on the device-type selected by dynamic reconfigure.

**Comment by aruisdante** [comment]
Obviously for the moment we're just focused on the IMU we're actually using, but the system should be flexible enough to easily add additional devices if/as we expand the driver.

**Comment by mitchellwills** [comment]
What were you thinking about for settings
What I have right now is

Device Configuration:
- serial baud rate
- serial parity
- serial data bits
- serial stop bits
- serial flow control

Device Calibration:
none

As i'm not as familiar with kalman filters I wasn't as sure what to put here. Would it just be confidence for x, y, z?

**Comment by aruisdante** [comment]
Yep, that's pretty much it. Take a look in the data sheet and pull out any values that look like they're sensor noise/confidence values. We basically initialize the filter with a known sensor noise (that will be straight from the data sheet on devices like these) and basically estimation covariance (again there should be some values here, they're pretty much the variance on a given reading from the expected value). Remember the devices have x,y,z gyro, x,y,z accelerometer, and some (not the ones we're using) have x,y,z heading.

Adam Panzica

Graduate Student,
WPI Department of Robotics Engineering
RIVeR Lab
WPI SRR Team AERO

**Comment by mitchellwills** [comment]
Should those values be returned in their raw x, y, and z components or as matrices?

**Comment by aruisdante** [comment]
The noise should be a CloumnVector, the Sigmas (covar) is a SymmetricMatrix with the values along the diagonal and the rest zeros.
